### ISSUE TITLE
Automate website updates

### ISSUE THREAD

**Issue by bmw** [certbot/website#189]
We'd need to come up a convention on the Certbot side to prevent changes about unreleased features from going live, but this saves devs time and causes website improvements to be deployed faster.

**Comment by SwartzCr** [comment]
@bmw @vbrown608 and I talked about this and decided on what we think is a workable option.
1) remove the ability to push to master without review & delegate a small group of maintainers to do these PRs (like with the certbot/certbot repository)
2) set up Travis to send the built website to another repository (with a branch name of the PR in question) so that the reviewer can manually check the built website before accepting the PR
3) replace the build procedure that we have with the static files generated by travis after a merge to master (like step 2, but for master rather than PRs)
4) have one of us push these static files to an internal EFF git repo that the hosting server will continually pull from (much like the current set-up)

@pde we'd like to hear your thoughts on this - if you have any issues with this, we're happy to talk about it more in depth in person, otherwise we'd like to implement this.

The advantages we see are:
* One standard build environment (Travis) that's not living locally on people's machines
* A better workflow for visually reviewing PRs
* Less ability for many changes to be held up before a website update
* Less gating on the update process, it's easier to add an EFF account to the internal git repo to push an update than it is for someone to set up the Docker build environment.
The possible disadvantages we see are:
* More reliance on the safety of Github and Travis

**Comment by pde** [comment]
Overall I'm happy to delegate this to you and Vivian to figure out Noah.

The only question I'd ask is, am I correct in gathering that we'll now be committing the built website to our public master repo? Something to consider before doing that is whether contributors will get confused and try to edit the built site rather than the source files. That happens with `certbot-auto` all the time, and it's a pain that's worth avoiding if you can.

**Comment by vbrown608** [comment]
As I understand it, the built files will be committed to a separate repo - something like certbot/website-builds. That repo could be private.

Sounds like this will be my first task now that I'm back at EFF. I'm going to start poking around to see if Travis is capable of performing and pushing the build as described in (2).

@bmw, were you hoping to see a live/rendered version of the built files for each PR? I don't remember if we discussed this. Github pages would make it possible to view the master branch, but not the PR branches. On top of that, I think it would be weird to have another publicly-accessible version of the certbot site floating around, associated with an EFF repo. Just wanted to make sure seeing the raw built files or pulling to view them in a browser locally is okay.

**Comment by bmw** [comment]
Being able to see a rendered version of each PR would be ideal, but its not necessary if that's exceptionally difficult to do in a way that everyone is happy with.

I don't have a strong opinion about who should be able to access this staging repo and/or rendered website. I see your point about having another version of the site floating around is a little awkward, but having a site associated with this public repo doesn't seem too crazy to me if the intent of the page is clear by having something like "staging" in the URL of the site.

Again, I don't have a strong opinion here though so if anyone else does, I think we can just follow their plan.

**Comment by vbrown608** [comment]
I think it could make sense to expose a single branch of the website-builds repo as a rendered website. That could either be master (for a final check before deploying) or a branch that always shows a build of the most recent PR.

Unfortunately Github pages doesn't give us great options for URLs. We can
1. Use a github-provided domain like https://certbot.github.io/website-builds
2. Use a custom domain without HTTPS. Github pages doesn't support HTTPS for custom domains. This seems very sad for a Certbot staging site.

If either of those are appealing to tech projects I can set that up. I think setting up a separate server for staging that automatically pulls from the website-builds repo is overkill for this round of automation but it's certainly possible if we want to do that in the future.

**Comment by bmw** [comment]
Yeah I agree setting up a separate server for this is overkill, especially if any significant amount of code has to be written to support what we want to do with it.

I think the main value of being able to see the rendered pages is to be able to look at a PR before it is merged. While being able to see the most recent PR may get us that, it's a bit unwieldy and often won't show us what we want to see. With this in mind, I think we can skip hosting the built website somewhere else and just automate the build allowing easy releases and the ability for people to download the files and review them locally.

@SwartzCr, as the other person who reviews most of the PRs here, does this sound good to you?

**Comment by vbrown608** [comment]
Staging site aside, this seems to be working on my fork. I'll need to add a repo to the Certbot org for the built files and add a deploy key for travis to that repo. Looks like I have enough permissions to go ahead and do that. 

Can I get a +1 from someone involved in Certbot before I make those changes? was thinking I'd call it website-builds.

**Comment by SwartzCr** [comment]
+1!

**Comment by mfb** [comment]
There was an interesting video that came out yesterday about future gitlab features, including auto deploying an app instance for every merge request, so reviewers can review the app/site itself not just the code.

**Comment by vbrown608** [comment]
@bmw do you need anything from webdev for #4 of the plan outlined above? Based on the internal wiki page for the certbot.eff.org it sounds like an internal repo from which the site pulls automatically already exists.

**Comment by bmw** [comment]
You're right that step 4 is already done and we don't need anything from webdev.
