### ISSUE TITLE
Hosting provider search only searches the visible providers

### ISSUE THREAD

**Issue by ohemorange** [certbot/website#465]
It doesn't search across all the categories, only the one currently showing.

**Comment by ohemorange** [comment]
Proposed solution: create a tab that includes all hosting providers as the default.
![After user tests - Github - 2 issues - revised explanation (needs review), “all hosting providers” tab](https://user-images.githubusercontent.com/1227205/64898367-c0f1d700-d63b-11e9-991e-5c4eb39761ce.png)

**Comment by lschatzkin** [comment]
I modified the design slightly and want to make sure these changes are okay. It's a little tricky to have tabs that have borders and have them responsive too. I added a darker gray bg to help define the area. LMK what you think. @okaysoraya 
![tabs-wide](https://user-images.githubusercontent.com/852512/69579807-16c1f400-0f88-11ea-9ba7-4f7282a7f909.png)

**Comment by okaysoraya** [comment]
Hmmm, let’s tweak the colors when I’m in the office. The dark grey feels a little heavy so I’d like to use something that’s a bit more subtle.

> On Nov 25, 2019, at 1:33 PM, schatzkin <notifications@github.com> wrote:
> 
> I modified the design slightly and want to make sure these changes are okay. It's a little tricky to have tabs that have borders and have them responsive too. I added a darker gray bg to help define the area. LMK what you think. @okaysoraya
> 
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 


—
Soraya Okuda
she/her || they/them

Want to teach digital security? Check out EFF's Security Education Companion at 
https://sec.eff.org/ and Surveillance Self-Defense at https://ssd.eff.org.

┳┻| 
┻┳| 
┻┳|•.•)   <3 support eff
┳┻| ⊂ﾉ     eff.org/donate
┻┳|

**Comment by lschatzkin** [comment]
Sure thing, I just threw that gray in there so let's pick a nicer one.

**Comment by okaysoraya** [comment]
Let's try this version-- full-width tabs, so that a background color is not needed.

Additionally, as the "all HTTPS support" tab now demands more reliance on the iconography as a faster way of scanning whether HTTPS support is provided, we should change the alt-text of the accompanying green check, yellow dash and red x icons to be more meaningfully descriptive for users scanning the chart with text-to-speech software. Let's maybe change the alt-text for the tiny icons (in the chart only) to:

+ green check --> full HTTPS support
+ yellow dash --> partial HTTPS support
+ red x --> no HTTPS support
