### ISSUE TITLE
Change CentOS/RHEL 8 instructions to use EPEL 8 when packages exist

### ISSUE THREAD

**Issue by gopalraha** [certbot/website#492]
With reference to https://github.com/certbot/certbot/issues/7202

**Comment by bmw** [comment]
I made progress on this in #557, but I closed the PR for now until the need for the PowerTools repo is addressed either through documentation or https://github.com/certbot/certbot/issues/7886.

**Comment by FelixSchwarz** [comment]
just fyi: Somehow the acme test suite does not pass in our build environment (https://bugzilla.redhat.com/show_bug.cgi?id=1834530) but everything works fine in a regular virtualenv. I assume this is a due to an "insecure" test certificate and some RHEL hardening.

I'll try to debug this problem in the next days but just wanted to say that your mock removal is really appreciated. certbot 1.4 is on its way for Fedora users at least (CentOS 7 needs extra love because of a Red Hat packaging error: https://bugzilla.redhat.com/show_bug.cgi?id=1834528).

**Comment by gopalraha** [comment]
Hi there, 

Now the Certbot RPM package is available on default CentOS 8 Repository.

Seems like issue has been fixed.

If possible close this ticked and mark it as a resolved

Thanks and regards,
Gopal Raha

**Comment by bmw** [comment]
This ticket hasn't been closed yet because I'm not sure the concerns in my comment above have been addressed yet.

Certbot 1.4.0 should be packaged in EPEL 8 soon, but it also looks like https://fedoraproject.org/wiki/EPEL#Quickstart was updated to tell people to install the `PowerTools` repo addressing the problem through documentation

@FelixSchwarz, do you know if the instructions there to enable EPEL and the `codeready-builder-for-rhel-8-*-rpms` repo will allow people to install Certbot on RHEL 8 or are there other repositories that are required right now?

**Comment by FelixSchwarz** [comment]
The `PowerTools` reference is present in the wiki [since September 2019](https://fedoraproject.org/w/index.php?title=EPEL&type=revision&diff=553585&oldid=552455). When that repo is enabled EPEL's certbot 1.3 installs fine and I'm using it without any problems.

In practice many users do not enable the `PowerTools` repo because it is not needed so they are not aware of that repo at all (at least I was not until I tried to package certbot 1.3 and needed `python3-mock`).

certbot 1.4 will be available in the testing repo soon and should hit stable in ~2 weeks.

The only limitation right now is that EPEL 8 is missing the `digitalocean` plugin (see [rhbz #1813735](https://bugzilla.redhat.com/show_bug.cgi?id=1813735)) because a required library is not available there. I'm working on that but it mostly depends on the current package maintainers.

**Comment by bmw** [comment]
Thanks for the info!

My question was mainly if you knew the situation on RHEL 8 because the current wiki instructions do not tell RHEL 8 users to enable the PowerTools repo.

**Comment by FelixSchwarz** [comment]
"PowerTools" is the CentOS name. "Code Ready Builder" repo is the same but from Red Hat for RHEL. Same packages, different name.

**Comment by FelixSchwarz** [comment]
btw: certbot 1.4 was just pushed to the EPEL 8 stable repo and should not require `python3-mock` anymore (so users don't need the PowerTools repo anymore). The digitalocean plugin is also on its way (will take ~1 week until stable).

**Comment by bmw** [comment]
Awesome!

Thanks for the update @FelixSchwarz.
