### ISSUE TITLE
Add EFF logo above the fold

### ISSUE THREAD

**Issue by krcarlson** [certbot/website#500]
Let's add the EFF logo above the fold on Certbot.

Here's the solution our design team came up:

* 40 pixel thin banner above
* EFF monogram logo + text on same baseline ("a project of the Electronic Frontier Foundation"
* banner links back to EFF.org and should appear on each page.
* text: Roboto slab regular; unsure about size in rem
* colors: -- EFF logo #EC1E1E -- banner background #2E2E2E -- text: #D9D9D9

Note: Design tested these colors on webaim.org and they pass. Design team has the EFF monogram SVG.

**Comment by wioux** [comment]
Sorry I'm late to this discussion -- I just started reviewing the attached PR.

![Peek 2020-02-25 17-53](https://user-images.githubusercontent.com/6469642/75305059-d594e680-57f9-11ea-9461-8cafdcfe9e73.gif)

Having the logo up top as a leading full width banner overhanging every page seems like overkill. In the PR it's part of the fixed nav, which stays still as you scroll. That space should have a high premium since it is always occluding some amount of content underneath. With the logo bar, the nav, and the fixed bar of social media links at the bottom, about 35% of the page consists of fixed always-on-top elements as I try to read the site on a Pixel 2.

We could remove the fixed positioning for just the logo banner, but I'm also concerned that it pushes the installation instructions further down the page.

You have to glance through a lot of elements and iconography now to reach the installation instructions go-to and it feels distracting, especially since the two large panels are animated. There's an alternating full width/partial width gray/white background thing going on too which contributes.

Can we ask design for an option that doesn't increase the header height? My own suggestion would be to put the line "a project of the Electronic Frontier Foundation" *after* the name of the site, on the opposite side:

![Screenshot_2020-02-25_17-34-11](https://user-images.githubusercontent.com/6469642/75305363-ba76a680-57fa-11ea-967c-5021f16eb15f.png)

**Comment by lschatzkin** [comment]
The fix banner with EFF is part of the branding we are doing now for all EFF sites, so that part can't be changed.
