### ISSUE TITLE
opensuse instructions need replacing

### ISSUE THREAD

**Issue by zoopla-jb** [certbot/website#721]
The opensuse instructions use snap which is completely unnecessary and is not supported in opensuse. This is true for Leap and Tumbleweed
 
This one step would replace steps 2-6 on this [page](https://certbot.eff.org/lets-encrypt/tumbleweed-nginx) :

2. install certbot with `sudo zypper in python3-certbot`

Any additional plugins can be found by typing `zypper se certbot`.

I would also suggest renaming Leap 15.0 to Leap 15.x, as 15.0 and 15.1 are end of life, whilst 15.2 and 15.3 are still active.

**Comment by bmw** [comment]
Using snap may not be supported by the opensuse maintainers, however, there are instructions from the snap team for installing snap on opensuse at https://snapcraft.io/docs/installing-snap-on-opensuse.

We have chosen to recommend snaps wherever possible because it ensures people are able to a Certbot package that stays up-to-date and does things like configures automated renewal by default. If you don't want to use snaps, there are other options available, but we're planning to continue to recommend snaps in our instructions here so I'm going to close this issue.

Thanks for pointing out the Leap version number. I've opened https://github.com/certbot/website/pull/722 to fix that.
