### ISSUE TITLE
Add IBM i instructions 

### ISSUE THREAD

**Issue by ThePrez** [certbot/website#732]
Hello. I'd like to contribute IBM i instructions, starting with the "Other" software stack. 
It would be similar to https://certbot.eff.org/lets-encrypt/otherpip-other but some things are different on IBM i. 

I've not worked with Jekyll before (I can figure it out) and am having trouble figuring out where to start. If someone could give me a pointer to which files to create/modify, I'd really appreciate it

Documenting the rough steps here, just because the steps are fresh in my head (I just went through the process)

IBM i Certbot instructions
----------------------------------------------------------------------------------
Set up `PATH`
```
PATH=/QOpenSys/pkgs/bin:$PATH
export PATH
```
Install requisites
```
yum install python39-pip python39-cryptography
```
Create virtual environment
```
python3.9 -m venv --system-site-packages /opt/certbot
```
Install certbot
```
/opt/certbot/bin/pip install certbot
```
Run certbot
```
/opt/certbot/bin/certbot certonly --standalone
```
  or 
```
/opt/certbot/bin/certbot certonly --webroot
```

confirm that Certbot worked

To renew, 
```
/opt/certbot/bin/certbot renew
```

**Comment by bmw** [comment]
Thanks for the offer to add these instructions, but I don't think we want them. I think the instructions at https://certbot.eff.org/lets-encrypt/otherpip-other should work on IBM i, however, I think special attention needs to be paid to

> If you're having trouble installing cryptography, you may need to install additional dependencies. See the [cryptography project's site](https://cryptography.io/en/latest/installation.html#building-cryptography-on-linux) for more information.

and 

> These packages may have slightly different names on other distributions; a search such as "augeas on <your_system_name>" will probably yield helpful results.

from step 2.

We've actually been trying to keep our instructions slightly more generalized lately as we found maintaining very specific instructions for each OS to be infeasible.

Because of that, I'm closing this issue, but if you think I missed something or you'd like me to reconsider, leave a comment and let me know.
