### ISSUE TITLE
Missing apache and nginx dependency in certbot pip instructions

### ISSUE THREAD

**Issue by jamesyoung-15** [certbot/website#814]
I ran into [this](https://github.com/certbot/certbot/issues/9998) issue when following [Nginx on Pip](https://certbot.eff.org/instructions?ws=nginx&os=pip) instructions, where the instructions didn't mention installing the plugin and would run into `The requested nginx plugin does not appear to be installed` error after running `sudo certbot --nginx`

I think adding something about installing the plugins (apache, nginx, etc.) after step 5 or 6 will be helpful for noobs like me  (eg. `sudo /opt/certbot/bin/pip install certbot-nginx`).

**Comment by bmw** [comment]
this seems like a fairly recent regression based on https://web.archive.org/web/20240821082216/https://certbot.eff.org/instructions?ws=nginx&os=pip

@wgreenberg, i'll just ping you about this for now since you've been working with E&D the most on the certbot site, but if you'd prefer i do something else (file a help ticket, etc.) please just let me know

**Comment by wgreenberg** [comment]
brought this up w/ syl and we think we've got a fix! and i'm happy to triage the site issues that end up on github

**Comment by wgreenberg** [comment]
This has been fixed.
